name: autogen
on:
  push:
    branches: [main, develop]
    paths:
      - "lua/**.lua"
      - ".stylua.toml"
      - "README.md"

# Cancel any in-progress CI runs for a PR if it is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  autogen:
    name: "(vimdoc|formatting)"
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Generate docs with panvimdoc
        uses: kdheepak/panvimdoc@v2.7.1
        with:
          vimdoc: autocommit
          description: plugin for automatically committing code changes to version control
      - name: Apply stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=.stylua.toml lua/
          version: 0.14.1
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "chore: autogen (vimdocs+formatting)"
          branch: ${{ github.head_ref }}
          file_pattern: lua/ doc/color-roulette.txt
